### ISSUE TITLE
Is this project production ready?

### ISSUE THREAD

**Issue by koddr** [pyGrowler/Growler#18]
Hello.

Is this project production ready? Maybe some projects already runs with Growler?

Nice to listen use cases 👍

**Comment by akubera** [comment]
Short answer: no.

The biggest thing left to do is parameterized routes, something like `/page/<int:pagenum>` or `/:foo/:bar/`. I have a half-implemented submodule I've been sitting on for a few months, but haven't dedicated the time to complete it; I'll probably work on that over the holidays.

Until that is done, there isn't a whole lot of benefit that growler provides; I know of nobody using it in production besides the growler.rocks site, which has been running the (static) site successfully for over a year.

**Comment by koddr** [comment]
@akubera Thanks for answer.

**Comment by smurf-U** [comment]
@akubera Any update? Is parameterized routes working? If yes how?
