### ISSUE TITLE
Handle binary data uploads

### ISSUE THREAD

**Issue by kyeatman74** [pyGrowler/Growler#19]
I'm running into a problem with uploading binary data (longer than 32K) to a pygrowler-based service.  It looks like the responder is not handling the 'EXPECT': '100-continue' header.   Can this be added in?  It can probably be handled similar to the aiohttp module.

**Comment by akubera** [comment]
Yeah I never got around to implementing Continue or MultiPart parts of the standard like I'd hoped. I'll look into this soon

**Comment by akubera** [comment]
Good news: I finally wrote the fix for this in https://github.com/pyGrowler/Growler/commit/737169457673bdab6be1983e0f3689e160a8ec3a.
