### ISSUE TITLE
Consider an integration with uvloop

### ISSUE THREAD

**Issue by nikolay** [pyGrowler/Growler#4]
Read about [uvloop](https://github.com/MagicStack/uvloop) [here](http://magic.io/blog/uvloop-blazing-fast-python-networking/).

**Comment by akubera** [comment]
https://news.ycombinator.com/item?id=11632292

Actually, it already works with uvloop! I'll do a write up this weekend on my experiences with performance.

I was impressed with how easy it was to enable and how well it worked.

**Comment by jfmatth** [comment]
However, for us Windows users, uvloop integration would be bad, since UVLOOP isn't Windows compatible (from what I read).

**Comment by nikolay** [comment]
@jfmatth Well, [libuv](http://libuv.org/) is supported on Windows, so, it's just a matter of time and volunteering: https://github.com/MagicStack/uvloop/issues/14.

**Comment by jfmatth** [comment]
well my bad, sorry.
