### ISSUE TITLE
Example in README.md doesn't work?

### ISSUE THREAD

**Issue by jfmatth** [pyGrowler/Growler#6]
Thank you for creating growler, I think it looks great!  

I was trying the examples and they work fine, but I copied and pasted the example on the main README and it doesn't work with the pip version of growler (0.7.2).

Here's the error
```
File "hello.py", line 14, in <module>
    app.use(Renderer("views/", "jade"))
TypeError: __init__() takes 2 positional arguments but 3 were given

```

**Comment by akubera** [comment]
Ah yes, I completely changed how Renderer worked a couple months ago. I'll update the example tomorrow. 

Thanks for letting me know!

[Example0](https://github.com/pyGrowler/Growler/tree/dev/examples/example0) *should* be a working example of 'renderable' templates.
