### ISSUE TITLE
Using Uvloop in Growler

### ISSUE THREAD

**Issue by machbio** [pyGrowler/Growler#8]
I recently came across Growler, it looks pretty good framework to move away from Flask that I am currently using.

But I have seen some improvements on the loop with https://github.com/MagicStack/uvloop - the benchmark seems to show it is better event loop as compared to Asyncio Event loop. so can I replace the Event loop from the current example to use Uvloop - just wanted to know if I am missing anything.

Asyncio Loop
   
    loop = asyncio.get_event_loop()
    app = App('GrowlerServer', loop=loop)

Uvloop
   
     loop = uvloop.new_event_loop()
     app = App('GrowlerServer', loop=loop)

I understand that #4 its been brought forward - but should it not be as straightforward as given above.

**Comment by akubera** [comment]
The way I'm using uvloop currently is 
```python
import uvloop
asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
```
at the beginning of my __main__.py, before the app is created. This is how http://growler.rocks is running (which is currently as single page site and any framework/accelerator is unnecessary).

Let me know if the other syntax works.

**Comment by machbio** [comment]
Thank you,  looks like there is no need of worrying about uvloop integration
